## CHAPTER 2. 시퀀스
#### 2.1 내장 시퀀스 개요
- 컨테이너 시퀀스: 서로 다른 자료형의 항목들을 담을 수 있는 list, tuple, collections.deque 형
- 균일 시퀀스: 단 하나의 자료형만 담을 수 있는 str, bytes, bytearray, array 형
- 가변 시퀀스: list, bytearray, array, collection.deque 형
- 불변 시퀀스: tuple, str, bytes 형

#### 2.2 지능형 리스트와 제너레이터 표현식

In [2]:
symbols = '$%!@#'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 37, 33, 64, 35]

In [3]:
symbols = '$%!@#'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 37, 33, 64, 35]

python 2.x 버전에서는 List Comprehension 스코프가 전역으로 설정되어서 같은 변수명을 사용하는 경우<br>
변수에 저장된 값이 날라갔었다.

    >>> x = 'my precious'
    >>> dummy = [x for x in 'ABC']
    >>> x
    'C'

In [4]:
x = 'ABC'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

ABC
[65, 66, 67]


In [5]:
symbols = '$%!@#'
beyond_ascii = [ord(s) for s in symbols if ord(s) < 60]
print(beyond_ascii)

beyond_ascii = list(filter(lambda c: c < 60, map(ord, symbols)))
print(beyond_ascii)

[36, 37, 33, 35]
[36, 37, 33, 35]


In [6]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)

tshirts = [(color, size) for size in sizes 
                         for color in colors]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


In [7]:
symbols = '$%!@#'
print(tuple(ord(symbol) for symbol in symbols))

import array
array.array('I', (ord(symbol) for symbol in symbols))

(36, 37, 33, 64, 35)


array('I', [36, 37, 33, 64, 35])

In [8]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


#### 2.3 튜플은 단순한 불변 리스트가 아니다

In [9]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'),
               ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

for country, _ in traveler_ids:
    print(country)

BRA/CE342567
ESP/XDA205856
USA/31195855
USA
BRA
ESP


In [10]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)

print(longitude)

33.9425
-118.408056


In [11]:
divmod(20, 8)

(2, 4)

In [12]:
t = (20, 8)
divmod(*t)

(2, 4)

In [13]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [14]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [15]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [16]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [17]:
# *는 단 하나의 변수에만 적용할 수 있지만, 어떠한 변수에도 적용 가능
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [18]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [19]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.43333, -99.133333)),
    ('New York-Newarl', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.54778, -46.635833))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0 :
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |     19.43 |  -99.1333
New York-Newarl |     40.81 |  -74.0204
Sao Paulo       |    -23.55 |  -46.6358


In [20]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [21]:
tokyo.population

36.933

In [22]:
tokyo.coordinates

(35.689722, 139.691667)

In [23]:
tokyo[1]

'JP'

In [24]:
City._fields

('name', 'country', 'population', 'coordinates')

In [26]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', (28.613889, 77.208889))])

In [27]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: (28.613889, 77.208889)


#### 2.4 슬라이싱

In [28]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [29]:
l[2:]

[30, 40, 50, 60]

In [30]:
l[:3]

[10, 20, 30]

In [31]:
l[3:]

[40, 50, 60]

In [32]:
s = 'bicycle'
s[::3]

'bye'

In [33]:
s[::-1]

'elcycib'

In [34]:
s[::-2]

'eccb'

In [37]:
s[slice(1, 5)]

'icyc'

In [39]:
slice(1, 5, 2)

slice(1, 5, 2)

In [43]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [45]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [46]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [47]:
l[2:5] = 100

TypeError: can only assign an iterable

In [48]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

#### 2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기

In [49]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [50]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [60]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [61]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [62]:
weird_board = [['_'] * 3] * 3 # <- 같은 리스트 참조 3개를 생성한다.
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [63]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [64]:
# weird_board
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

In [65]:
# list comprehension
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
    
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [66]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

#### 시퀀스의 복합 할당

In [67]:
l = [1, 2, 3]
id(l)

4398069960

In [68]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [69]:
id(l)

4398069960

In [70]:
t = (1, 2, 3)
id(t)

4418716584

In [72]:
t *= 2
id(t)

4418081896

In [73]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [74]:
t

(1, 2, [30, 40, 50, 60])

In [75]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


#### 2.7 list.sort()와 sorted() 내장 함수

In [78]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [79]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [80]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [81]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [82]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [83]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

#### 2.8 정렬된 시퀀스를 bisect로 관리하기

In [98]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

In [99]:
argv = ''

if argv == 'left':
    bisect_fn = bisect.bisect_left
else:
    bisect_fn = bisect.bisect
    
print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [100]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [101]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%d ->' % new_item, my_list)

10 -> [10]
0 -> [0, 10]
6 -> [0, 6, 10]
8 -> [0, 6, 8, 10]
7 -> [0, 6, 7, 8, 10]
2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


#### 2.9 리스트가 답이 아닐 때

In [104]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.051056611520245765

In [105]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [107]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.051056611520245765

In [108]:
floats2 == floats

True

In [109]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [110]:
memv[0]

-2

In [111]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [112]:
memv_oct[5] = 4

In [113]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [114]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
type(a)

numpy.ndarray

In [116]:
a.shape

(12,)

In [119]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a[2]

array([ 8,  9, 10, 11])

In [121]:
a[2, 1]

9

In [122]:
a[:, 1]

array([1, 5, 9])

In [123]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [124]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [126]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [127]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [129]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])